name: PHP CodeSniffer

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  phpcs:
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@0.0.2
    with:
      name: Run PHP CodeSniffer
      run: composer phpcs
      php-version: '8.5'
