name: PHPStan

on:
  push:
    branches:
    - main
    paths:
    - '**.php'
    - phpstan.neon
    - phpstan.neon.dist
    - phpstan-baseline.neon
    - composer.json
    - composer.lock
    - .github/workflows/phpstan.yml
  pull_request:
    branches:
    - main
    paths:
    - '**.php'
    - phpstan.neon
    - phpstan.neon.dist
    - phpstan-baseline.neon
    - composer.json
    - composer.lock
    - .github/workflows/phpstan.yml

jobs:
  phpstan:
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@0.0.2
    with:
      name: Run PHPStan
      run: composer phpstan
      php-version: '8.5'
