name: Tests

on:
  push:
    branches:
    - main
    paths:
    - '**.php'
    - composer.json
    - composer.lock
    - phpunit.xml
    - phpunit.xml.dist
    - .github/workflows/tests.yml
  pull_request:
    branches:
    - main
    paths:
    - '**.php'
    - composer.json
    - composer.lock
    - phpunit.xml
    - phpunit.xml.dist
    - .github/workflows/tests.yml

jobs:
  test:
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-tests.yml@0.0.2
    with:
      php-versions: '["8.5"]'
      coverage-php-version: '8.5'
